<?php

namespace AppBundle\Repository;

/**
 * LicenseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseeRepository extends \Doctrine\ORM\EntityRepository
{
}
