<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findByActivePublicPost()
    {
        return $this->createQueryBuilder('p')
            ->where('p.activePost = true')
            ->andWhere('p.publicPost = true')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function findByActivePrivatePost()
    {
        return $this->createQueryBuilder('p')
            ->where('p.activePost = true')
            ->andWhere('p.publicPost = false')
            ->getQuery()
            ->getResult();
    }

}

